development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: domain_review_development
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  database: domain_review_test
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  database: domain_review_production
  username: 
  password: 
  socket: /var/run/mysqld/mysqld.sock
